name: PyVADesign
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - asttokens=3.0.0
  - backcall=0.2.0
  - biopython=1.84
  - biotite=0.38.0
  - cairo=1.18.0
  - cffi=1.17.1
  - dna_features_viewer=3.1.3
  - ipykernel=6.14.0
  - ipython=8.4.0
  - matplotlib=3.9.3
  - matplotlib-base=3.9.3
  - matplotlib-inline=0.1.7
  - numpy=1.26.4
  - python=3.9
  - primer3-py=2.0.3
  - requests=2.32.3
  - scikit-learn=1.2.2
  - scikit-learn-extra=0.3.0
  - scipy=1.13.1
  - pip
  - wheel
prefix: